# Generated by Django 5.2.7 on 2025-10-15 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('main_genre', models.CharField(choices=[('ACC', 'Acción'), ('COM', 'Comedia'), ('DRM', 'Drama'), ('FAN', 'Fantasía')], default='ACC', max_length=10)),
                ('description', models.CharField(max_length=1000)),
                ('img_url', models.CharField(default='no_image', max_length=2000)),
                ('status', models.CharField(choices=[('EM', 'Emisión'), ('PROX', 'Proximamente'), ('FIN', 'Finalizado')], default='FIN', max_length=12)),
                ('type', models.CharField(choices=[('AN', 'Anime'), ('PE', 'Pelicula'), ('OV', 'Ova')], default='AN', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=1000)),
                ('img_url', models.CharField(default='no_image', max_length=2000)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animepage.anime')),
            ],
        ),
    ]
