# Generated by Django 5.2.7 on 2025-11-23 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=1000)),
                ('img_url', models.CharField(default='no_image', max_length=2000)),
                ('type', models.CharField(choices=[('AN', 'Anime'), ('PE', 'Pelicula'), ('OV', 'Ova')], default='AN', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('prefix', models.CharField(max_length=5, unique=True)),
                ('description', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('color', models.CharField(max_length=7, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('observation', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=1000)),
                ('img_url', models.CharField(default='no_image', max_length=2000)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animepage.anime')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='main_genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='animepage.genre'),
        ),
        migrations.AddField(
            model_name='anime',
            name='statusRef',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='animepage.status'),
        ),
    ]
