# Generated by Django 5.2.7 on 2025-10-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='img_url',
            field=models.CharField(default='no_image', max_length=2000),
        ),
        migrations.AlterField(
            model_name='anime',
            name='img_url',
            field=models.CharField(default='no_image', max_length=2000),
        ),
    ]
