# Generated by Django 5.2.7 on 2025-11-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animepage', '0002_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('emision', 'En emisión'), ('finalizado', 'Finalizado'), ('proximamente', 'Proximamente')], max_length=20, unique=True)),
                ('color', models.CharField(choices=[('#EF4444', 'Rojo'), ('#22C55E', 'Verde'), ('#3B82F6', 'Azul')], max_length=7, unique=True)),
            ],
        ),
    ]
