# Generated by Django 5.2.7 on 2025-11-23 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animepage', '0003_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='status',
        ),
        migrations.AddField(
            model_name='anime',
            name='statusRef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='animepage.status'),
        ),
        migrations.AlterField(
            model_name='status',
            name='color',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
