# Generated by Django 5.2.7 on 2025-11-23 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animepage', '0004_remove_anime_status_anime_statusref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='statusRef',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='animepage.status'),
        ),
    ]
